let mapleader=" "
set encoding=utf-8
set nocompatible
syntax on
set number
set wrap
set showcmd
set wildmenu
set hlsearch
exec "nohlsearch"
set incsearch
set ignorecase
set smartcase
set cursorline

noremap J 5j
noremap K 5k
noremap <LEADER><CR> :nohlsearch<CR>

map s <nop>
map S :w<CR>
map Q :q<CR>
map R :source $MYVIMRC<CR>


call plug#begin('~/.vim/plugged')

Plug 'vim-airline/vim-airline'
Plug 'hzchirs/vim-material'
Plug 'connorholyday/vim-snazzy'

call plug#end()

colorscheme snazzy
" Palenight
let g:material_style='palenight'
set background=dark
colorscheme vim-material



